### ISSUE TITLE
Use fiziko with pdflatex

### ISSUE THREAD

**Issue by pizdjuk** [jemmybutton/fiziko#10]
Is it possible? Or at least with Texlive 2019

**Comment by jemmybutton** [comment]
Yes, you can use either [`emp`](https://tug.ctan.org/macros/latex/contrib/emp/emp.pdf) or [`gmp`](https://tug.ctan.org/macros/latex/contrib/gmp/gmp.pdf) packages for that. Here's an example:
```latex
\documentclass{article}
\usepackage[shellescape, latex]{gmp}

\begin{document}
	\begin{mpost}
		input fiziko;
		draw sphere.c(2cm);
	\end{mpost}
\end{document}
```
NB: you need to run `pdflatex --shell-escape yourfile.tex` for this example to work.

Not sure about TexLive 2019, but there should be nothing in fiziko.mp which didn't work in 2019 version, and both `emp` and `gmp` are fairly old, so they definitely are in the 2019 release.

**Comment by pizdjuk** [comment]
Thank you! And what shell-escape is for?

**Comment by jemmybutton** [comment]
With shell-escape you can have everything compiled in one run, and without it you need to run `mpost` separately and then re-run `pdflatex` in order to get your image placed within the document. `gmp` produces a shell script for that, so what you'd need to do if `shellescape` option is not enabled in `gmp` package settings, is to run something like this: `pdflatex yourfile.tex && sh yourfile+mp.sh && pdflatex yourfile.tex`. For more details see `gmp` documentation.

**Comment by pizdjuk** [comment]
Thanks again!

BTW, I just tried the same example, but with sphere.s and it didnt work. I mean that nothing is drawn. Is it a bug? I use fiziko from a texlive distro I have

**Comment by jemmybutton** [comment]
You are welcome!

> BTW, I just tried the same example, but with sphere.s and it didnt work. I mean that nothing is drawn. Is it a bug? I use fiziko from a texlive distro I have

It should have worked (but it's `sphere.c` not `sphere.s`). It's difficult to say exactly what went wrong without at least your .log file.

**Comment by jemmybutton** [comment]
`sphere.s` doesn't exist as of now. What result did you try to achieve?

**Comment by jemmybutton** [comment]
You are welcome!

`sphere.s` (stippling) was only [introduced in 2022](https://www.ctan.org/ctan-ann/id/mailman.475.1644355508.3195.ctan-ann@ctan.org), so it wasn't there in TeXLive 2019. You can download `fiziko.mp` from the repo and put it in the directory you work in, and it should work.

Sorry, I somehow forgot about it.
