### ISSUE TITLE
solidSurface, but textured as wood

### ISSUE THREAD

**Issue by pizdjuk** [jemmybutton/fiziko#11]
It would be cool to be able to make a solidSurface, but with texture as woodenThing. Right now it is some kind of complicated to do: one needs to define a curve, then define normals to a curve a make a closed path around.

**Comment by jemmybutton** [comment]
Do you mean something like this?
```
vardef woodenSurface (expr surfacePath) =
	save surfaceOutline;
	path surfaceOutline;
	surfaceOutline := surfacePath --  reverse(offsetPath(surfacePath) (-1/4cm)) -- cycle;
	woodenThing(surfaceOutline, 0)
enddef;
path p;
p := (0,0){dir(30)}..(5cm, 0)..{dir(30)}(10cm, 0);
draw woodenSurface(p);
```
![image](https://github.com/user-attachments/assets/5f2f2c7a-8bef-4e39-97b8-363e50eadf30)

**Comment by pizdjuk** [comment]
lol, yes 😅

BTW it takes _veery long_ to compile, but I think its ok, since I unterstood how the wooden texture is calculated :)

**Comment by jemmybutton** [comment]
It's indeed very slow, especially since the texture is calculated for the whole rectangle containing the shape, and then cropped. I'll think about how to optimize it in some way.

**Comment by jemmybutton** [comment]
I optimized wood texture for `woodenThing` quite a bit, and added `woodenSurface` function with [this](https://github.com/jemmybutton/fiziko/commit/20f78fcb2f369431051f90ab35f41c4fa6385ef6). Syntax for `woodenSurface` is as described above. It's still not fast, but at least now it doesn't try to draw a whole block of wood to then clip it, and instead only draws what is necessary.

**Comment by jemmybutton** [comment]
In general, I think, now it can be closed, but feel free to re-open/open another issue, if something else is needed.
